# source: http://blog.kubernetes.io/2017/03/advanced-scheduling-in-kubernetes.html
apiVersion: v1
kind: Pod
metadata:
  name: some-pod
  namespace: default
spec:
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: service
            operator: In
            values:
            - frontend
        # built-in node labels:
        topologyKey: kubernetes.io/hostname
  containers:
  - name: name
    image: nginx
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 8080
    resources:
      requests:
        memory: "64Mi"
        cpu: "100m"
      limits:
        memory: "128Mi"
        cpu: "200m"
