apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0003
  labels:
    type: local
spec:
  capacity:
    storage: 200M
  accessModes:
    - ReadWriteOnce
#  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: "/tmp/data"